name: Check Typos
on:
  pull_request

jobs:
  typo-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      FORCE_COLOR: 1
      TYPOS_VERSION: v1.19.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: check typos
        uses: crate-ci/typos@v1.22.4
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          config: ./_typos.toml